### ISSUE TITLE
I think printf.js has an incorrect comment

### ISSUE THREAD

**Issue by mmorearty** [winstonjs/logform#10]
The comment for `printf.js` seems incorrect — perhaps it was partially copied and pasted from `colorize.js`, because it says stuff about color, and as far as I know, `printf` has nothing to do with colors:

```javascript
/*
 * function printf (templateFn)
 * Returns a new instance of the printf Format that creates an
 * intermediate prototype to store the
 * level colors to `info` objects. This was previously exposed
 * as { colorize: true } to transports in `winston < 3.0.0`.
 */
```

**Comment by DABH** [comment]
Seems reasonable -- happy to consider a PR to make this documentation more accurate :) Thanks for spotting!
