### ISSUE TITLE
Last Release 1st Feb 2019, 3 outstanding commits

### ISSUE THREAD

**Issue by tchetwin** [winstonjs/logform#102]
The last release was 2.1.2 on 2019-02-01. Two small(?) features and a fix were added to master since then which can be seen here: https://github.com/winstonjs/logform/compare/2.1.2...master

Could a new release be cut? Are there any blockers?

**Comment by t-yng** [comment]
I have problem that I use winston timestamp format with function because latest version type definition is old.

```
# This is example
const logger = winston.createLogger({
    timestamp({
        format: () => 
    }),
});
```

occurred type check error

```
Argument of type '{ format: () => string; }' is not assignable to parameter of type 'TimestampOptions'.
  Types of property 'format' are incompatible.
    Type '() => string' is not assignable to type 'string'.
```

This problem was fixed and merged to master branch.

I hope new release, If you can. 😄

**Comment by tchetwin** [comment]
Hi @DABH, I see PR activity to both this repo and [winstonjs/winston](https://github.com/winstonjs/winston/compare/3.2.1...master) itself continues though neither has seen a release since Q1 2019.

Do you know of any plans for the accumulated changes from either project to be released?

**Comment by DABH** [comment]
The recommendation for now is to use the master branches of the packages from your package.json, rather than the last released version.  I can’t do releases of Winston on npm so would need @indexzero ’s help to cut a release.

**Comment by indexzero** [comment]
@DABH thank you for being so on top of maintenance when I have not. 

You feel good about cutting the release yourself if you're granted publish rights? 🤓

**Comment by DABH** [comment]
@indexzero Sure thing.  I am ready to live with the consequences of cutting and supporting a Winston release ;) Hope all is well.

**Comment by indexzero** [comment]
The long road is long. You are now an owner on npm. Sincere thanks for continuing to do the hard maintenance work 💪

Would love to talk about async iterators at some point before August. The path to a clean browser build does not include node streams but custom async iterators to interop with WhatWG streams (among others).

**Comment by DABH** [comment]
Thank you sir.  And, sounds good — I may have some time in July if you feel like discussing or implementing something together.

**Comment by philippfo9** [comment]
hey, is there an update planned on npm as the types are still the old ones?

**Comment by tchetwin** [comment]
v2.2.0 was just released, thanks for all your work @DABH!

**Comment by DABH** [comment]
You are welcome - just finished releases of all of the Winston stack and will hopefully find incrementally more time now so I can burn down a bit of the issue/PR backlog going forward.

**Comment by philippfo9** [comment]
@DABH thanks for the update and your great work!
