### ISSUE TITLE
Moving to chalk

### ISSUE THREAD

**Issue by ThrowsException** [winstonjs/logform#126]
This project has a dependency on `colors.js` which the creator of has recently pushed breaking changes to npm. It appears he is no longer interested in maintaining his projects and instead is using them to grief the community by releasing broken versions. Is there an interest in migrating the library to say `chalk.js`

**Comment by dapplion** [comment]
Yes please

**Comment by DABH** [comment]
AFAICT we're already pinned to 1.4.0 so should be fine.  I have also been working to resolve the issues with colors.js, so we are not turning a blind eye toward this -- hopefully in the next day or two everything will be resolved.  Thanks for raising this concern though!

**Comment by philBrown** [comment]
> AFAICT we're already pinned to 1.4.0

Only on `master`. Still needs a new tagged release

**Comment by DABH** [comment]
Yeah I will after dinner probably

**Comment by DABH** [comment]
This fix is released in logform 2.3.2 and Winston 3.3.4

**Comment by ThrowsException** [comment]
@DABH appreciate the quick response.

**Comment by ThrowsException** [comment]
@DABH And also trying to help with the colors situation. Unfortunate circumstances all around =/
