### ISSUE TITLE
Please release new version with pinned colors

### ISSUE THREAD

**Issue by Apollon77** [winstonjs/logform#129]
Hi,

after fixing the issue with https://github.com/winstonjs/logform/commit/aa4eefdc2591f8d5fb7a198e73937db512da36e9 please also release a new version so that the JavaScript ecosystem also get that great fix :-)

Would be cool to get this fix!

Thank you very much!

**Comment by DABH** [comment]
Yeah I will

**Comment by DABH** [comment]
This fix is released in logform 2.3.2 and Winston 3.3.4

**Comment by Apollon77** [comment]
Thank you very much!

**Comment by AlCalzone** [comment]
@DABH FYI, these releases don't show up in the Github Releases tab - not sure if that's intended.

**Comment by DABH** [comment]
Wasn’t intended, is that a problem?  I used vbump to do this release but will probably switch to np for future releases since that does automatically create GH releases for example.

**Comment by DABH** [comment]
No problem, thanks for bringing it to my attention :)
