### ISSUE TITLE
Update colors dep version to latest

### ISSUE THREAD

**Issue by Aniket-Engg** [winstonjs/logform#130]
Hello,

`colors` has released a latest 1.4.2 version. Older version in this repo's package.json is making use of `winston` difficult. Please consider.

Related to https://github.com/winstonjs/logform/pull/128

**Comment by forty** [comment]
Why not migrate to chalk which seems better maintained ? I can open a PR is there is interest.

**Comment by forty** [comment]
(also winstonjs is one of our only deps still relying on colors, all others have already migrated to chalk, so it will probably also do one less dep for many project)

**Comment by DABH** [comment]
I think the OP here is trolling, Winston has used colors@1.4.0 for two years or so.

Colors meets our needs and is lighter weight than chalk, but if we can’t get the issues with colors resolved in the next few days, will consider migrating.

**Comment by forty** [comment]
Ok, thanks, I see the version has been pinned which works too. That said if the ecosystem is largely migrating to chalk (from what I can see in my own dependencies, I cannot say if it's representative), the fact that colors is light weight is going to be made irrelevant by the fact that many project using Winston are going to now depends on colors+chalk.

**Comment by wbt** [comment]
Though #126 is more on-topic, note here that while logform doesn't currently have any direct or indirect dependencies on `chalk`, `winston` has 5:

```
├─┬ @babel/core@7.16.7
│ └─┬ @babel/code-frame@7.16.7
│   └─┬ @babel/highlight@7.16.7
│     └── chalk@2.4.2 deduped
├─┬ eslint-config-populist@4.2.0
│ └─┬ eslint@4.19.1
│   ├─┬ babel-code-frame@6.26.0
│   │ └── chalk@1.1.3
│   ├── chalk@2.4.2
│   ├─┬ inquirer@3.3.0
│   │ └── chalk@2.4.2 deduped
│   └─┬ table@4.0.2
│     └── chalk@2.4.2 deduped
└─┬ mocha@9.1.3
  └─┬ log-symbols@4.1.0
    └── chalk@4.1.2
```
