### ISSUE TITLE
[Bug]: json space is not working

### ISSUE THREAD

**Issue by lake2** [winstonjs/logform#199]
### The problem

combile(
        json({
            space: 2,
        })
)

logger.info('2 %j', { a: { b: { c: { g: { e: { f: 1 } } } } } });

output   2 {"a":{"b":{"c":{"g":{"e":{"f":1}}}}}}

### What version of Logform presents the issue?

2.4.1

### What version of Node are you using?

v16.12.0

### 🔎 Search Terms

json splat

**Comment by wbt** [comment]
Sorry, I'm not sure how to parse this error report.  You can try asking a version of this on StackOverflow as it seems likely to be a usage question, but you'll need a more completely-filled out version of the template for folks there to understand the question too.
