### ISSUE TITLE
[Bug]:  A computed property name in an interface must refer to an expression whose type is a literal type or a 'unique symbol' type

### ISSUE THREAD

**Issue by speedofsound99** [winstonjs/logform#245]
### The problem

Getting these errors now trying to use winston. These were introduced in latest version.

node_modules/logform/index.d.ts:11:3 - error TS1169: A computed property name in an interface must refer to an expression whose type is a literal type or a 'unique symbol' type.

11   [LEVEL]?: string;
     ~~~~~~~

node_modules/logform/index.d.ts:12:3 - error TS1169: A computed property name in an interface must refer to an expression whose type is a literal type or a 'unique symbol' type.

12   [MESSAGE]?: any;
     ~~~~~~~~~

node_modules/logform/index.d.ts:13:3 - error TS1169: A computed property name in an interface must refer to an expression whose type is a literal type or a 'unique symbol' type.

13   [SPLAT]?: any;
     ~~~~~~~

### What version of Logform presents the issue?

2.5.0

### What version of Node are you using?

18.12.0

### If this worked in a previous version of Logform, which was it?

2.4.2

### Minimum Working Example

_No response_

### Additional information

_No response_

### 🔎 Search Terms

computed property name error

**Comment by can-keklik** [comment]
Same here, latest version broke our build too

**Comment by speedofsound99** [comment]
workaround for me for now, include logform in package.json and set version to 2.4.2

**Comment by esadalez** [comment]
Same here :(

**Comment by TheNhatAT** [comment]
I have the same issue but logform is dependency of winston lid in my code. How can I fix it ? any helps will be appreciated .

**Comment by Mr-zsy** [comment]
> I have the same issue but logform is dependency of winston lid in my code. How can I fix it ? any helps will be appreciated .

me too~

**Comment by can-keklik** [comment]
doing as @speedofsound99 says works actually

**Comment by Abirami061299** [comment]
Fix this issue as much as possible

**Comment by TheNhatAT** [comment]
you guy can add "skipLibCheck": true" into tsconfig. work for me

**Comment by screencomuser** [comment]
From the release notes "All the improvements in this release are from first-time contributors"

**Comment by slk5611** [comment]
I'm also getting same issue and broken down the build.

**Comment by akuter-bc** [comment]
same here

**Comment by slk5611** [comment]
Thank you @TheNhatAT work for me. **add "skipLibCheck": true" into tsconfig.**

**Comment by cecia234** [comment]
same here

**Comment by LeonMacN** [comment]
same here!!!! any update???

**Comment by can-keklik** [comment]
skipLibCheck: true would be an overkill and would TS less useful btw. You should avoid using permanently
