### ISSUE TITLE
[Bug]: Add timestamp to TransformableInfo interface

### ISSUE THREAD

**Issue by jpramos123** [winstonjs/logform#250]
### The problem

Created a` winston` log format using typescript:

```typescript
const logFormat = printf(({ timestamp, level, message }) => {
    return `${timestamp} ${level}: ${message}`;
})
```
When I try running `tsc` it returns:

```
src/logger/logger.ts:28:29 - error TS2339: Property 'timestamp' does not exist on type 'TransformableInfo'.

28 const logFormat = printf(({ timestamp, level, message }) => {
```

My guess is that it is missing in the Interface at: https://github.com/winstonjs/logform/blob/master/index.d.ts#L8-L15

I modified my local `TransformableInfo` interface under `node_modules/logform/index.d.ts` to the code below, and worked just fine:

```typescript
export interface TransformableInfo {
  level: string;
  message: any;
  timestamp: any;
  [LEVEL]?: string;
  [MESSAGE]?: any;
  [SPLAT]?: any;
  [key: string | symbol]: any;
}

``` 

### What version of Logform presents the issue?

v2.5.1

### What version of Node are you using?

v16.19.0

### Minimum Working Example

1. Install `winston`
2. Create a `logger.ts` file with:

```typescript
import { createLogger, format, transports } from 'winston'
import config from 'config'

const levels = {
    error: 0,
    warn: 1,
    info: 2,
    http: 3,
    debug: 4,
}

const { combine, timestamp, printf } = format;

const logFormat = printf(({ timestamp, level, message }) => {
    return `${timestamp} ${level}: ${message}`;
})

export const Logger = createLogger({
    level: config.get("LOG_LEVEL"),
    levels,
    format: combine(
        timestamp(),
        logFormat,
        format.json()
    ),
    transports: [new transports.Console()]
})
```

3. Run `tsc` command

### 🔎 Search Terms

TransformableInfo, logform

**Comment by wbt** [comment]
What version of TypeScript are you using when observing this?

**Comment by wbt** [comment]
Closing for issue maintenance based on linked PR and the assumption that the answer is <4.4, but we can reopen if that's an incorrect assumption.

**Comment by jpramos123** [comment]
@wbt The version being used is: `^4.4.4`

**Comment by wbt** [comment]
What version specifically is it that's running?
