### ISSUE TITLE
winston.format.timestamp({ format: <YYYY-MM> }) doesn't work with format parameter (issue with solution)

### ISSUE THREAD

**Issue by ivanmatiaspascual** [winstonjs/logform#4]
Hi!,

i discover that:

./logform/timestamp.js:

14 module.exports = format(function (info, opts) {                                                                                                                                    
15   if (opts.format) {
16     info.timestamp = typeof opts.format === 'function'
17       ? opts.format()                                                                                                                                                              
18       : formatDate(**new Date()**, opts.format); // <<<<<<<<<<<<<<<<<<<<< **the solution!**
19   }
20     
21   if (!info.timestamp) {                                                                                                                                                           
22     info.timestamp = new Date().toISOString();                                                                                                                                     
23   }                                                                                                                                                                                
24                                                                                                                                                                                    
25   if (opts.alias) {
26     info[opts.alias] = info.timestamp;
27   }                                                                                                                                                                                
28                                                                                                                                                                                    
29   return info;
30 });

Sorry if i dont respect de standards to report an issue.

**Comment by MartinMuzatko** [comment]
Agreed! This fix works! I'm providing a PR.

**Comment by MartinMuzatko** [comment]
By the way: you really should add tests for timestamp @indexzero

**Comment by nfantone** [comment]
Exactly this. ☝️

**Comment by indexzero** [comment]
Fixed by #11. Thanks @MartinMuzatko @ChrisAlderson
