### ISSUE TITLE
Remove colorizer from transport formatter

### ISSUE THREAD

**Issue by Codex-** [winstonjs/logform#61]
Currently if you add a colorizer to a transport there is no way to remove it without recreating the entire formatter on the transport in question. I would have expected that the implementation of uncolorize would behave in such a way that if colorize as a function were present in the combined format that it would also remove it (or there be another means of removing the colorize formatter from the combined formatter, although I couldn't find anything like this in the source or docs.)

Consider the following example:
Creating a basic winston logger, with a simple message format, the default colorizer, and a timestamp:
```ts
import * as winston from 'winston';

const basicFormat = winston.format.printf(
  msg => {
    return `${msg.timestamp} - ${msg.level}: ${msg.message}`;
  }
);

const logger = winston.createLogger({
  transports: [
    new winston.transports.Console({
      format: winston.format.combine(
        winston.format.colorize(),
        winston.format.timestamp(),
        basicFormat,
      )
    }),
  ],
});

logger.info(`thanos`);
logger.warn(`was`);
logger.error(`right`);
```

This prints the expected output with the default colours:
![image](https://user-images.githubusercontent.com/8297838/47394990-67fa2580-d781-11e8-81a0-2dcb6874dd75.png)

Currently the only way to remove the colours without recreating the transport (which can be cumbersome if you have various transports) is to use uncolorizer at the end of your combined format:
```ts
logger.transports[0].format = winston.format.combine(
  logger.transports[0].format,
  winston.format.uncolorize(),
)
```

Which yields the expected output with said colours removed:
![image](https://user-images.githubusercontent.com/8297838/47395150-fcfd1e80-d781-11e8-86f6-fedee0130d9f.png)

The problem with doing this is that each logged message is then going through the combined formatter as:
1. Set the colours
2. Perform other formatting operations
3. Strip the colours

Which of course is adding extra operations to each log.

Although this may be intended behaviour, in that your desired approach to this is to either recreate the transports effected or at the least recreate their formatters?

**Comment by DABH** [comment]
Yeah, my guess at a "best practice" would indeed be to just edit a transport's `.format` if you want to change the formatting behavior.  However, maybe in your case I'd do something like
```js
const f1=winston.format.combine(
        winston.format.colorize(),
        winston.format.timestamp(),
        basicFormat,
      );
const f2=winston.format.combine(
        winston.format.timestamp(),
        basicFormat,
      );
```
Then you can just alternate between `f1` and `f2`, which avoids redundant `uncolorize` operations.

Alternatively, you could use some clever scoping and do something like (_not tested_)
```js
const c = true;
// no-op if c is false, otherwise it's winston.format.colorize()
const maybeColorize = (info, opts) => c ? winston.format.colorize(info, opts) : info;
const f1 = winston.format.combine(
        const maybeColorize,
        winston.format.timestamp(),
        basicFormat,
      );
...
//somewhere later
c = false;
// hopefully scope magic makes colors go away now?
```
Lmk if you have any other concerns/ideas/suggestions!
