### ISSUE TITLE
JSON formatter doesn't stringify attributes in a consistent order

### ISSUE THREAD

**Issue by jorgelf** [winstonjs/logform#90]
Issue in Linux with Winston 3.2.1 and Node 10.15.1.

Though this isn't a critical error, I find it annoying that the _JSON_ formatter doesn't stringify the resulting object with the attributes always in the same order.

For example, I have a _File_ transport with the _errors_, _splat_, _timestamp_ and _JSON_ formatters and the following lines result in different log lines:
```javascript
logger.info('TEST TEST');
logger.info('TEST %s', 'TEST');
```
```json
{"message":"TEST TEST","level":"info","timestamp":"2019-04-05T15:09:52.076Z"}
{"level":"info","message":"TEST TEST","timestamp":"2019-04-05T15:09:52.077Z"}
```

Not sure if that change in behaviour could be considered a bug in _Winston_ itself, but I think these problems could easily be avoided by having the _JSON_ formatter stringify in a consistent order, most likely by using _fastSafeStringify.stableStringify_ instead of the library's default method. Maybe it could be configurable with a new option?

Right now I'm avoiding this annoyance by setting a custom formatter before the _JSON_ one that resets the options' keys in alphabetical order, in case someone has this problem as well:
```javascript
winston.format(options => {
        var keys = Object.keys(options).sort();
        for (var i = 0, len = keys.length; i<len; i++) {
            var value = options[keys[i]];
            delete options[keys[i]];
            options[keys[i]] = value;
        }
        return options;
})()
```

**Comment by DABH** [comment]
Totally valid request.  If you'd like to add a `stable` option to the JSON formatter that uses `stableStringify` if `true`, we'd be happy to accept a PR.  I imagine there's some performance cost to doing that sorting, which is why it's off by default.

**Comment by jorgelf** [comment]
Thanks @DABH.

PR created, hope everything is fine.

**Comment by stefaanv** [comment]
This did this trick for me 
```javascript
    const formatForFile = winston.format.printf((info) => {
      const uid = info.uid ? `,"uid":"${info.uid}"` : ''
      const meta = info.meta ? `,"meta":${JSON.stringify(info.meta)}` : ''
      return `{"timestamp":"${info.timestamp}","level":"${info.level}","context":"${info.context}","message":"${info.message}"${uid}${meta}}`
    })
```

**Comment by nickcuper** [comment]
you can try this one, work for me
```typescript
format.printf(({ timestamp, level, message, ...leftOver }) =>
                    JSON.stringify({
                        timestamp,
                        level,
                        message,
                        ...(leftOver || {}),
                    }),
                )
```
